In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.03585158, -0.20815994, -0.11973856, -0.3077195 ,  0.53398407,
         0.6708862 ,  0.97552896,  0.07943092, -0.25320235,  0.29473296]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07470176, 0.06287793, 0.0686909 , 0.05691937, 0.13207096,
        0.15144788, 0.20538457, 0.0838296 , 0.06010859, 0.10396851]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(1.8875139)

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8558 - loss: 0.4970
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9557 - loss: 0.1495
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9666 - loss: 0.1089
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9718 - loss: 0.0877
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9775 - loss: 0.0708


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9756 - loss: 0.0784


[0.07842864096164703, 0.975600004196167]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0115710e-08, 4.2145389e-09, 3.4772391e-05, 1.1737513e-03,
        1.1013045e-09, 3.0060184e-05, 8.6127681e-11, 9.9874157e-01,
        6.8938202e-06, 1.2866914e-05],
       [9.1590827e-08, 1.7340545e-04, 9.9982041e-01, 5.4567540e-06,
        7.2669768e-16, 5.9251313e-08, 2.4362592e-07, 1.2131029e-12,
        3.5437665e-07, 4.3352783e-14],
       [1.3851709e-07, 9.9963820e-01, 3.4147863e-05, 9.5331061e-06,
        2.2455992e-05, 3.2482276e-06, 2.9520613e-06, 2.2164999e-04,
        6.7364657e-05, 3.8507329e-07],
       [9.9994493e-01, 5.4243568e-11, 1.6924965e-05, 1.3084308e-06,
        1.6399437e-07, 6.7000656e-07, 3.4476252e-05, 9.9418472e-08,
        1.5362946e-07, 1.4113969e-06],
       [1.8687602e-05, 7.1472304e-09, 1.2114140e-05, 1.3898217e-07,
        9.9108618e-01, 6.3053949e-07, 2.8492093e-05, 2.3806240e-05,
        2.7107797e-06, 8.8271843e-03]], dtype=float32)>